language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gmagno
  password:
    secure: mAbfKBZACEA/50NjkWZJCXw+qgWV9W5mfvvVis3+5GnVf09DtQ87LElgLxrOsRyukAJDkfbhZA+DDZmzQINgo2AiSITXI9Sk2lJZl6ACYEgj/80CIyUvN666TaEuF8L2mpnIy8/5OF2cS+duAO/gje9pBmGjfdbpLu1a+q7bwJaAq/QjRAwfQk+FwhhX+GPmutLY6vF/VnrH05G+HzENBNyUHwJBHJvSjkLbZdaMAYysZN/OwcSuCinILLcT47Caa1UExAj2eBv9JFdsTpekTE/4JTqjduikzaxTD74dQySbzYC+8smmYUfh4S1nT2nKT2GD2NXXam0Th3D9rJpIBAJ6W7dX/bZlNwd1U4QKMz/j4aspKdE1Tp45eXPs2CWnm1SP74eMvN7dP1S/Oqb/aQdyS6HLHyli7TWR9sMItju7StzhDYeOAnwRqrx/DfgTLyVKOmYzz/gCsKRpRd+f2mTzkt63QiAieJNlGZAwdgeInRAnVIsPwuGDyIonhtLKv3H+p5dtWRSpglRS0BWPV8O1EU+Z81VZV5RZ4C57C/iPNNooxBlJ/Oi9SgzGclzVS47gImbETe74mYgNNQ5uZyCXYESmHwdrcJLQsPfyiHVRtOPoc0cvkF/4RuY0TUz8rtGAkST5LL9oW9hMgci5Kt+hLJRYSz6SC60BYq755Ng=
  on:
    tags: true
    repo: gmagno/pycut
    python: 3.8
