language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gmagno
  password:
    secure: crGl6mbuI7E35mysER7tu2z+P0X4sUPEf3sETE+ufDaZRWVHxxItK1ETgS/S1nmqUVCevj4qlm1pojmm0qpSKp4fM87tzTwUwXE38TJ9QloM5FWLQibZHuJi6gtOY61cfFhJcGMgxW8Ur5N4yjIYAvP4fZt+HoFrA3gxaEpeOMxXET6VuNYz3Fkd8BatjEyDwxPEmvXHy3ZH3vJ5yJzarGfir4K6GHKyRyaVAniOgjohE+Va1PdDSUEcujk2R+Ui1erOtYaVNeIazo/17yfwyN7sYaP8Td4FOpbP8TkfPDlbPs2MDGBaN7TXXE7ruzoBdQhwqkY1R9pcBIWYuS+ZkFPN8rZzcvMSd6lBUoWoeoi/1o+cp3D/H3aWGod6eYr2QKzJNZcEXxcGVT+W2hdZi1/YBt0IM4jKjiEifS7kidL7y1j6VzV8kiwkyUo+Nql8tB2wOgeg9K2u1RSVP4+8TduDOSrDbm4Io81cqHnb+IKbdeVNqXoI3r2jG8AW9dpx4u4wB34cirPExyuduNEdlOGUNXzbgKZMH7HIKYErer7tgdOya3K/3bdKiqYHEtTlYHMETI8ivz5kWLay0WSedLIa616B3t2mEEWSXCNlokuqJW5J5h8jevJ7MxUbzBq6cIRiqoH4Vs9Ae19hsuz3VxfJ5deiXSUte0lA/24LnDU=
  on:
    tags: true
    repo: gmagno/pycut
    python: 3.8
