language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gmagno
  password:
    secure: gso3ytTjK/wuzKkzqUT0BwaPqL1ACNhZyebK6isRESH2YnXaF5O+/WB/6AwhurUyLFhgrbo1KI5G5aGPK/60PjsE2EYTllANZ2e11Q0+e1cZtTyJu8agPFLSHaHZLWyNicH52fEwhdQMMq2KUcdN3yiFc17XZpOELFDuYv67XNBPjIwuMZotjn2+94Z27BAKyLTSahoiY0dCGg6ArSuzKae/FcJnb09HYk29+50hy4v+1AfS+RDgJAd4nnVRH38F3kXPd5XqbwZsKPMsGQAbgtFPkWKnbdyk/lHqCrYpujmuF/HbcG2SZsul5ANDWfED5uUCq/3pSdAwYWPl8uhRfV9RxH5RTYKz951sqfXttVvNhIP3/4wL+nqVhfSTKuCXaTf0qK6sV0/HQzYk8sVsxIs3rx7Wl9f8/bugdfIure+mmerYowaqdGsSmp5+MUi4/xy312zuKi8Iv206EzL9BHDaPtwS8wiWHlAuHnWkUOcesuYHVnJpnFoQTMTYdycHLJFJlYCUmYu2nWTvsfk4jYWmehlMppdOew3okKg+jcMRc6du3WXd8FZqOOBvvIIEYxuqu8oXQcxn91+sF39ntFwvkI/LpkHd4362p515ap6fA8LDA75s54dgSHjmbC4M1vsLC2DO3q8D8kNTi1GoLc84S93bqFXgnFZEtN7zvuE=
  on:
    tags: true
    repo: gmagno/pycut
    python: 3.8
